// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-9xPJzWpPd8q1WVDfwWIKV63Yr3lu1Ls',
    appId: '1:966107244247:web:3eb5745ac91ac886ad3292',
    messagingSenderId: '966107244247',
    projectId: 'flutterfire-ui-codelab-ce6de',
    authDomain: 'flutterfire-ui-codelab-ce6de.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-ce6de.firebasestorage.app',
    measurementId: 'G-69QC9S9YYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnURCVFT7W1sfysKl8j9Ix9Qf9pKTe1vA',
    appId: '1:966107244247:android:e001fbf86f9fc94bad3292',
    messagingSenderId: '966107244247',
    projectId: 'flutterfire-ui-codelab-ce6de',
    storageBucket: 'flutterfire-ui-codelab-ce6de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy2MftDEJw70EBTlIBEVnmD86vZ3n9a_Q',
    appId: '1:966107244247:ios:4a225e8363ae1aefad3292',
    messagingSenderId: '966107244247',
    projectId: 'flutterfire-ui-codelab-ce6de',
    storageBucket: 'flutterfire-ui-codelab-ce6de.firebasestorage.app',
    iosBundleId: 'com.example.fire',
  );
}
